### ISSUE TITLE
cudnn error

### ISSUE THREAD

**Issue by zw20130717** [Jumpat/SegmentAnythingin3D#74]
i was running the command
 'python run_seg_gui.py --config=configs/llff/seg/seg_fern.py --segment \
--sp_name=_gui --num_prompts=20 \
--render_opt=train --save_ckpt'
when I received this cudnn error information. I have already installed the corresponding cudnn version to my cuda version(11.3) and still cant solve this problem. I'd appreciate it if anyone can offer me some advice on it.
![2024-06-04 15-48-34 的屏幕截图](https://github.com/Jumpat/SegmentAnythingin3D/assets/166890502/567b943f-4189-48f6-9407-9a7b37c75a30)

**Comment by zw20130717** [comment]
unable to find a valid cudnn algorithm to run convolution😢

**Comment by Jumpat** [comment]
Hi, have you checked 'nvcc -V' ? The 'CUDA_HOME' and 'LD_LIBRARY_PATH' ?

I think maybe torch cannot find the cuda. Does 'torch.cuda.is_available()' ?

**Comment by zw20130717** [comment]
> Hi, have you checked 'nvcc -V' ? The 'CUDA_HOME' and 'LD_LIBRARY_PATH' ?
> 
> I think maybe torch cannot find the cuda. Does 'torch.cuda.is_available()' ?
![2024-06-04 17-25-35 的屏幕截图](https://github.com/Jumpat/SegmentAnythingin3D/assets/166890502/be043b29-81ea-4c53-bbbf-424b470f383f)
yeah torch.cuda.is_available is true and cuda_home and ld_library_path is set.

**Comment by zw20130717** [comment]
> Hi, have you checked 'nvcc -V' ? The 'CUDA_HOME' and 'LD_LIBRARY_PATH' ?
> 
> I think maybe torch cannot find the cuda. Does 'torch.cuda.is_available()' ?
![2024-06-04 17-34-30 的屏幕截图](https://github.com/Jumpat/SegmentAnythingin3D/assets/166890502/408efed6-76fd-40ab-89b6-acfd5d8db534)
yeah torch.cuda.is_available is true and cuda_home and ld_library_path is set.

**Comment by zw20130717** [comment]
> Hi, have you checked 'nvcc -V' ? The 'CUDA_HOME' and 'LD_LIBRARY_PATH' ?
> 
> I think maybe torch cannot find the cuda. Does 'torch.cuda.is_available()' ?

hi

**Comment by zw20130717** [comment]
> Hi, have you checked 'nvcc -V' ? The 'CUDA_HOME' and 'LD_LIBRARY_PATH' ?
> 
> I think maybe torch cannot find the cuda. Does 'torch.cuda.is_available()' ?

yeah I THINK torch.cuda.is_available is true and cuda_home and ld_library_path is set.
![2024-06-04 17-34-30 的屏幕截图](https://github.com/Jumpat/SegmentAnythingin3D/assets/166890502/fc0f707a-7dca-4383-966d-c86df76eb3a9)

**Comment by Jumpat** [comment]
Hi, you may check [this](https://discuss.pytorch.org/t/unable-to-find-a-valid-cudnn-algorithm-to-run-convolution/78724/2) for some help. I have never met such problem in sa3d.

**Comment by zw20130717** [comment]
> Hi, you may check [this](https://discuss.pytorch.org/t/unable-to-find-a-valid-cudnn-algorithm-to-run-convolution/78724/2) for some help. I have never met such problem in sa3d.

Hi, I think I have solved the CUDNN problem but just received cuda-out-of-memory. May I ask your computer configuration to run this project? Mine is GEFORCE RTX 3070 with 8GB memory
